
spring:
  data:
    redis:
      host: redis
      port: 6379
      password:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:
        - id: cart-service
          uri: http://cart-service:8087
          predicates:
            - Path=/api/cart/**
          filters:
            - TokenRelay=
        - id: order-service
          uri: http://order-service:8086
          predicates:
            - Path=/api/order/**
          filters:
            - TokenRelay=
        - id: ui
          uri: http://frontend:3000
          predicates:
            - Path=/ui/**
          filters:
            - StripPrefix=1
        - id: static
          uri: http://frontend:3000
          predicates:
            - Path=/static/**
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/test
            authorization-uri: http://keycloak:8080/realms/test/protocol/openid-connect/auth
            token-uri: http://keycloak:8080/realms/test/protocol/openid-connect/token
            jwk-set-uri: http://keycloak:8080/realms/test/protocol/openid-connect/certs
            user-info-uri: http://keycloak:8080/realms/test/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          keycloak:
            provider: keycloak
            client-id: gateway
            client-secret: ${SECRET}
            authorization-grant-type: authorization_code
            scope:
              - openid
              - email
              - profile
              - roles

server:
  port: 8765
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: DEBUG

